### ISSUE TITLE
SourceShell Shader is clipping

### ISSUE THREAD

**Issue by Jindorf** [Jindorf/HoloOSCV2#1]
The SourceShell is around the player, but is not visible.

This is probably caused by the clipping pane settings of the Main Camera, that can't be changed below 0.01metres. Since the Camera is at position (0,0,0), it interferes with the Sourceshell at (0,0,0) with radius 1.

Possible fixes:

- Make the Sphere Mesh invisible and add 4 handlers at the edges of the shell that the user can interact with to rotate the sphere

**Comment by derTino89** [comment]
Probably the easiest way of making the SourceShell visable, is to change the "Cull Mode" to "off" and the "Rendering Mode" to "Additive" on the MRTK_Wireframe.
This way, you will get a transparent surface.

But: One is still unable to "grab" the SourceShell via ManipulationHandler.

Idea: 
A Button to enable/disable a "Callibration-Object" wich controls the "Master-azimuth and elevation." This could be:
                  - a Handler, sticked to the SourceShell,
                  - a miniature of the SourceShell itself
                  - a 2D UI with two faders 
                  - temporarily the camera itself (so the aimpoint of the viewer defines "north")
