### ISSUE TITLE
Azimuth/Elevation calculation for Sources is wrong

### ISSUE THREAD

**Issue by Jindorf** [Jindorf/HoloOSCV2#8]
Currently, the Azimuth/Elevation is calculated for the localposition of the Sources. So the position they get instantiated on is (0,0,0) for the calculation.

The calculation for Azimuth and Elevetaion of the sources should depend on the position of the shell.

**Comment by NM-GH** [comment]
Assigned.

Currently fixed angle calculation for Elevation.
