### ISSUE TITLE
Testing Environment

### ISSUE THREAD

**Issue by Jindorf** [Jindorf/HoloOSCV2#9]
Currently, if you want to fully test the project, you need to start it, then define an ipadress with port, update the reciever and then can manipulate sources / the shell.

It would be easier to have an developer Scene, where after pressing "play" I, as a developer, can press "play" and start moving/manipulating the spheres, with the option to change ipadress and port, but not as a neccessity.

Acceptance Criteria:
Make a new Scene, add the MRTK to the scene where IP and Port are set by default to local with port 8000. 
The Scene doesnt need an option for the Systemkeyboard.

**Comment by jsamus** [comment]
Can be achieved by removing/hiding the interface buttons and enabling the "Open on Awake" Option for the "Unicast to self" Mode which in turn automatically sets IP and Port to localhost:8000 after pressing "Play".
